[build]
builder = "NIXPACKS"

[phases.setup]
nixpkgsPackages = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mysqli",
  "php82Extensions.mbstring",
  "php82Extensions.openssl"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ./"
